apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: java_demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
      - image: 899488875890.dkr.ecr.ap-northeast-1.amazonaws.com/pipeline-demo-repo
        name: java_demo
        ports:
        - containerPort: 8080